#-------------------------------------------------------
# My 1st Actions
#
# Bender \ 2020-03-22
#-------------------------------------------------------

name: My-GitHubActions-Basics
env :
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: [ master ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in testing
      run : echo "Hello world from testing job"
    
    - name: Execute few commands
      run : |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder
      run : ls -la 
    
    - name: Git clone my repo 
      uses: actions/checkout@v1
        
    - name: List current folder
      run : ls -la 
      
  my_deploy:
    runs-on: ubuntu-latest
    needs  : [my_testing]
    env    :
      VAR1 : "This is Job Level Variable1"
      VAR2 : "This is Job Level Variable2"

    steps:
    - name: Print Hello Message in deploy
      run : echo "Hello world from deploy job"
      
    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var1 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is super local Enviroment variable"      
    
    - name: Printing Deployment package
      run : echo "Deployment package name is ${{ env.DEPLOY_PACKAGE_NAME }}" 
      
    - name: Lets test some packeges if they are here 1
      run : aws --version  
      
    - name: Lets test some packeges if they are here 2
      run : zip --version

